#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by localhost - 2024/12/31 13:33:11
# Search URL: http://localhost:8080/esg-search/wget?variable=pr&domain=AFR-44&experiment=rcp85&time_frequency=mon&driving_model=hadGEM2-ES,HadGEM2-CC,NCC-NorESM1-M,NCC-NorESM1-ME,MOHC-HadGEM2-CC,MOHC-HadGEM2-ES,MPI-ESM-LR,MPI-ESM-MR&institute!=(<Institute.ICTP:'ICTP'>,<Institute.DWD:'DWD'>)&latest=true
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://localhost:8080/esg-search/wget?variable=pr&domain=AFR-44&experiment=rcp85&time_frequency=mon&driving_model=hadGEM2-ES,HadGEM2-CC,NCC-NorESM1-M,NCC-NorESM1-ME,MOHC-HadGEM2-CC,MOHC-HadGEM2-ES,MPI-ESM-LR,MPI-ESM-MR&institute!=(<Institute.ICTP:'ICTP'>,<Institute.DWD:'DWD'>)&latest=true'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_200601-201012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/pr/v20140401/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_200601-201012.nc' 'SHA256' 'ac3eadfd1fdffa82d846dd3acdc789c7e790815d829169731faa758f6e644c38'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_201101-202012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/pr/v20140401/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_201101-202012.nc' 'SHA256' '57087170723b5c849c613c355477e2178bae3312ef6973a2cdb3310c4ad122f3'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_202101-203012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/pr/v20140401/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_202101-203012.nc' 'SHA256' 'cc1977e93c3eef4ed17b41a6caebcb65baab9b07c015b55fbba0ce32138afa4b'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_203101-204012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/pr/v20140401/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_203101-204012.nc' 'SHA256' '9b0f0f7efd055a322ba274aabd5dc2f49957f433d526e55aecb40a736c8ff37d'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_204101-205012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/pr/v20140401/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_204101-205012.nc' 'SHA256' 'd76ad8f3e3048873312f8cb88445d0fb466ee1fab5aaebd8bccd1a47edbffb81'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_205101-206012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/pr/v20140401/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_205101-206012.nc' 'SHA256' '44146edd0a166bc10366162798d42c86f9ad0ec50885274014650a2831b2a4fa'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_206101-207012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/pr/v20140401/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_206101-207012.nc' 'SHA256' '76da3f0a5132820d33a347824e35a6cce457cf09182c6de639e517d654df28f7'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_207101-208012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/pr/v20140401/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_207101-208012.nc' 'SHA256' '64de37274bad9943a392d90423dea1e8826ed729ee740d04900927e20702274b'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_208101-209012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/pr/v20140401/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_208101-209012.nc' 'SHA256' 'cfe26ac84f97c9ac13ddf5f8d55ceef512090d632c53893bd76b33cb0d5da6d5'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_209101-209911.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/pr/v20140401/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_209101-209911.nc' 'SHA256' 'e3f06e3f86cfc64cf9542bd4caf6dafcd6b07510f32aeee44caee26d77f7fac2'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_200601-201012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/pr/v20170620/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_200601-201012.nc' 'SHA256' '17cf20c7ca0f67ce4ff8069235acbc61f2687b4a5f18d4e292fa8cb62be6c9cf'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_201101-202012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/pr/v20170620/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_201101-202012.nc' 'SHA256' '141abe27323171e956329f0549b7f8cb2fb43f1a21464979a2c3da3f3d70c01e'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_202101-203012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/pr/v20170620/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_202101-203012.nc' 'SHA256' 'd41587a471163dd6003b9bb08586de9e789b81957d0661eb82fc45788c1cdd30'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_203101-204012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/pr/v20170620/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_203101-204012.nc' 'SHA256' '683fe31b0821d2f4e812d9fc484643d8d825fca6a41333801d3f049427eb1855'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_204101-205012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/pr/v20170620/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_204101-205012.nc' 'SHA256' '6048ec1a4efb41cb70131248de511b838ef36be9831c338ccaee22782b657aa8'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_205101-206012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/pr/v20170620/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_205101-206012.nc' 'SHA256' 'd84ec44bfd177af9518508fa21f14ea06bb2a207928567fe9fea27eb5b85dcea'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_206101-207012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/pr/v20170620/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_206101-207012.nc' 'SHA256' 'da8133e13586c60277cd4f72e834292c525da79aa2416558d8b7dce672224e96'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_207101-208012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/pr/v20170620/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_207101-208012.nc' 'SHA256' '9a88dde8734a6b29f3d23c7a338892d0fa98c19fed0205aea144ed2230ef2e73'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_208101-209012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/pr/v20170620/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_208101-209012.nc' 'SHA256' '02869a8d99402c315f29264ad6c53e33683a1ec31bc8f5eb8ea550b31bd760b5'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_209101-209912.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/pr/v20170620/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_209101-209912.nc' 'SHA256' 'b628f70b74b33810be67bca4c8b00b59debcd878db418ff32e30889ece36f7ac'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20051201-20110101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/pr/v20151029/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20051201-20110101.nc' 'SHA256' '3ad5d065d8fb089cfdc708c1d68d9976ebdec00483d8654a66d51d1a3d431d78'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20110101-20210101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/pr/v20151029/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20110101-20210101.nc' 'SHA256' '25f16e61ab432c065f9f279a3c64e5adb5992c387b42d6feec88163577828862'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20210101-20310101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/pr/v20151029/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20210101-20310101.nc' 'SHA256' '5771a583ca354504b156e3be0c51a04639400ef49696518f292af7089cf0dbdc'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20310101-20410101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/pr/v20151029/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20310101-20410101.nc' 'SHA256' '4d6df2724692c10220329220e581e7fc9144a271e19852f37c1f687f16c8c15b'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20410101-20510101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/pr/v20151029/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20410101-20510101.nc' 'SHA256' 'd65fcab19dae2e93ecbf1bcd407d7076255f7e9e0f50473cd1f9b7f191506454'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20510101-20610101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/pr/v20151029/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20510101-20610101.nc' 'SHA256' 'b7da13201a31502000abe208401e819cbf65a6c54c58072e09d73e98c3ee2769'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20610101-20710101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/pr/v20151029/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20610101-20710101.nc' 'SHA256' 'bb845472882d1b3ab5cd428c325762396fa7a0b4db7a40182d26ce92b0dee4bf'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20710101-20810101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/pr/v20151029/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20710101-20810101.nc' 'SHA256' '2fe9c3497b9f516e93c0adb2b11f56ad67b3514d77cfe6ac1e67b7cf2d439cf6'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20810101-20910101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/pr/v20151029/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20810101-20910101.nc' 'SHA256' '9187a6bc36192d08572d806147d42e8308374c34c9ed75db9601e50f2fbcc4b2'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20910101-20991201.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/pr/v20151029/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20910101-20991201.nc' 'SHA256' '3cc65e25bf029168aae9156b23412701c805ea2e1d0ae636513e11c69715487e'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_200601-201012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/pr/v20160802/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_200601-201012.nc' 'SHA256' 'de0763b65ec8d5e63a654ed79c950edef90623fda75b007384c6c9e0db4d4c42'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_201101-202012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/pr/v20160802/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_201101-202012.nc' 'SHA256' '22717d2e049172a716cb68364b753faa5296f99ecd4c9acebfff1b1ae9510712'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_202101-203012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/pr/v20160802/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_202101-203012.nc' 'SHA256' '85c2965c976ddc8a9825035736d332dfe8a31000b0b939c09d7a37107c095c41'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_203101-204012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/pr/v20160802/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_203101-204012.nc' 'SHA256' 'b017d2bda8786984cf0d394ab3de6e7ae87d9b4a574197ebc995bc190d104089'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_204101-205012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/pr/v20160802/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_204101-205012.nc' 'SHA256' 'e8c8ecdd99af8b2f4e6765154f6a8b7fe8a457384ccfcc967b5d3b8a643d5a26'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_205101-206012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/pr/v20160802/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_205101-206012.nc' 'SHA256' '733b70bee8bc919ae35a621d3e7910c750bff9ac151efdee5ec4358bd9bfad4d'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_206101-207012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/pr/v20160802/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_206101-207012.nc' 'SHA256' '9c2498c884bd1885c4072d455670849dfaa43a7fad97172abbb903d952672922'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_207101-208012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/pr/v20160802/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_207101-208012.nc' 'SHA256' '2e90588ca0e3ef45a0b82039af684b7d5d5ce8530b440eb6dd7ccc6af0693ee5'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_208101-209012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/pr/v20160802/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_208101-209012.nc' 'SHA256' '2fbcb9fc6888d03b7b71e140dfd7b2e46fbe531d93c1c8d42ab86c6fab6d6e6b'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_209101-209912.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/pr/v20160802/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_209101-209912.nc' 'SHA256' '51aa0a273ab9b83310541970d20f201b092e9c032a152d3be21a919d5de3205f'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_200601-201012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_200601-201012.nc' 'SHA256' '6e0e62a0d6ccac45cc8c8ddde8d31c696bf889d69cbee26082501a7e99cac9fa'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_201101-202012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_201101-202012.nc' 'SHA256' '13fd00f727784669afd54aef7d6a14bc0b4fb945f6f2590625158e72ec6dd912'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_202101-203012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_202101-203012.nc' 'SHA256' 'a211ad9093b73d31608de6f3600d453af69196f85c1992dd2f999f653e2758f6'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_203101-204012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_203101-204012.nc' 'SHA256' '8caba9e6788a51065ccf56e5d6e8a67b87269da766adf2f96fcd700983df405e'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_204101-205012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_204101-205012.nc' 'SHA256' 'eba314b9e368798a499250f83f006b1091618e5f3dfedcb40f356bcd0aa0d3bb'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_205101-206012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_205101-206012.nc' 'SHA256' 'c3e215ee3afaad11a80188b868b734dcb93b7a0f5b94ec7b7891b84aeb1052de'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_206101-207012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_206101-207012.nc' 'SHA256' '708968787316984c3e046436b10ac13c34475d8f41564a23fd64a6f280d96a78'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_207101-208012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_207101-208012.nc' 'SHA256' 'ff2f09f92c4bad319fccdbdcf5caa60090dee4750849976bbf1b26ca798477da'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_208101-209012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_208101-209012.nc' 'SHA256' 'ac9dceb1176036296fa22d4fa5b93b7f13ff34ba147ad30bb7eda5c31c4ee671'
'pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_209101-209912.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_209101-209912.nc' 'SHA256' 'e5c24201e100f514c6a6de5022d05a7ebdf101ede224c2a947658accae9fe3b0'
'pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_200601-201012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_200601-201012.nc' 'SHA256' '6b2b17fd31d9f1d283e941511e7acf0b4c90157c9b3e068fb4c2b92a306e6000'
'pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_201101-202012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_201101-202012.nc' 'SHA256' '0f91b44dbc0a525c3570578b230a2c2f0637068adb9e899471c0b965e3ae044e'
'pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_202101-203012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_202101-203012.nc' 'SHA256' 'd24fcb03cc61813a43768842eb1355347dc80a93512ed03062cf1977da1a013e'
'pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_203101-204012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_203101-204012.nc' 'SHA256' 'a2da2fb866396c9937f78a25b21ef064c5fa04572aac3f20b238b8db58829e24'
'pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_204101-205012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_204101-205012.nc' 'SHA256' '8215a93dedcfad3c725f6d2d4351e71c23596619be720f6bc5468b0ccbee017e'
'pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_205101-206012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_205101-206012.nc' 'SHA256' 'c96ae8224c17f57f405342edf0b4f2299679d5a1f8856babf42d7e67158c69a1'
'pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_206101-207012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_206101-207012.nc' 'SHA256' '9c9f4d1091b2afb98002c72ee3c12ea758075d68930da58bb18952eba03b2b29'
'pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_207101-208012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_207101-208012.nc' 'SHA256' 'c966ce5b047c16acd5d9450923f753dfa05f82dcaf7e82e4b89eba1f8029f013'
'pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_208101-209012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_208101-209012.nc' 'SHA256' 'd36e4fde64eea0ad923081ebf3dd42dab5d35611c806e162482e3ce7f5be0c2f'
'pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_209101-210012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/pr/v20130927/pr_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_209101-210012.nc' 'SHA256' '15dfd426f197d2af462845b331714452b95e46f204d554ec63111f613f26015a'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 60 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
