#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by localhost - 2024/12/31 13:33:12
# Search URL: http://localhost:8080/esg-search/wget?variable=tas&domain=AFR-44&experiment=rcp85&time_frequency=mon&driving_model=hadGEM2-ES,HadGEM2-CC,NCC-NorESM1-M,NCC-NorESM1-ME,MOHC-HadGEM2-CC,MOHC-HadGEM2-ES,MPI-ESM-LR,MPI-ESM-MR&institute!=(<Institute.ICTP:'ICTP'>,<Institute.DWD:'DWD'>)&latest=true
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://localhost:8080/esg-search/wget?variable=tas&domain=AFR-44&experiment=rcp85&time_frequency=mon&driving_model=hadGEM2-ES,HadGEM2-CC,NCC-NorESM1-M,NCC-NorESM1-ME,MOHC-HadGEM2-CC,MOHC-HadGEM2-ES,MPI-ESM-LR,MPI-ESM-MR&institute!=(<Institute.ICTP:'ICTP'>,<Institute.DWD:'DWD'>)&latest=true'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_200601-201012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/tas/v20140401/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_200601-201012.nc' 'SHA256' '2ce9c73990a28700b9e450740c8b9cb935795fc3378da95828907c4d3e2063e4'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_201101-202012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/tas/v20140401/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_201101-202012.nc' 'SHA256' 'f1ff89577a55067d9a71e42b4c5c182adc3d2dd8fb8b40dbc37bb8912d803f65'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_202101-203012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/tas/v20140401/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_202101-203012.nc' 'SHA256' '43b8ed869d0a1a57e3e22236d1bda65e1c83c6294d5e55e15f529bc4813d18a4'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_203101-204012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/tas/v20140401/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_203101-204012.nc' 'SHA256' '17878d15e74fbf478b8768cc3a3abfef1c576b836e5caa5d339f24d007a842ba'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_204101-205012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/tas/v20140401/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_204101-205012.nc' 'SHA256' '13660a91ce2acf9436f18fb6f6a2160d56852aa9d3e5b5131107f29c985c204d'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_205101-206012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/tas/v20140401/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_205101-206012.nc' 'SHA256' '55a753b878c15ded31f9369fb392a84489c45856360c95652ca112a32c848557'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_206101-207012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/tas/v20140401/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_206101-207012.nc' 'SHA256' 'b226f53171cfc325f971fe98f6c75798e6dc978e599561ae36ec006b82f34849'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_207101-208012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/tas/v20140401/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_207101-208012.nc' 'SHA256' 'f009524d06a8b3068be8b5cfd6e541998a0883be8a1919b08d5b5f1dec3b82bc'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_208101-209012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/tas/v20140401/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_208101-209012.nc' 'SHA256' '549d7a16d7ec533f678505aa90f70b2dc578c51eca4f1cb83ae00900feb11af5'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_209101-209911.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/CLMcom/MOHC-HadGEM2-ES/rcp85/r1i1p1/CLMcom-CCLM4-8-17/v1/mon/tas/v20140401/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_CLMcom-CCLM4-8-17_v1_mon_209101-209911.nc' 'SHA256' 'c2ef4e827dde192b0b552368a7c462ce560df07d1392f443d96180c5a4b1e765'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_200601-201012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/tas/v20170620/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_200601-201012.nc' 'SHA256' 'af4b3e9f1580048fcb814d736f8be6710b897e01bb1006e9a7bc7e927cf158e4'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_201101-202012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/tas/v20170620/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_201101-202012.nc' 'SHA256' '800f3c1bbd87c5d05bcee9766626361e579dd4c61076adf2027fa1b0ccdedf88'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_202101-203012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/tas/v20170620/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_202101-203012.nc' 'SHA256' '157cf44eb78547b22cc9ab57937281a1cb97d4bc4a68de52698e193911450a79'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_203101-204012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/tas/v20170620/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_203101-204012.nc' 'SHA256' 'fbd7ea4642056ebde3ccfebef42d63d5c413571a3701857ef1f5632d3b59c37b'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_204101-205012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/tas/v20170620/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_204101-205012.nc' 'SHA256' '56c8fee1115673de66f28ddf2869a0cf4ade9eb0e32609c297d800fdd7a50a9b'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_205101-206012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/tas/v20170620/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_205101-206012.nc' 'SHA256' '84b2c424902fa4db5d3726785a84230d5fb803d74a1921db6a82e5bf04c23dd5'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_206101-207012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/tas/v20170620/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_206101-207012.nc' 'SHA256' 'd5a90117b6fd77d58095335cfdd126576a070f4c57df5c8123e16a5e37d04b1f'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_207101-208012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/tas/v20170620/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_207101-208012.nc' 'SHA256' '8c3f00a41c72f93af940aa1f686122b5196b29f00be40b527af6b6542bbd661b'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_208101-209012.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/tas/v20170620/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_208101-209012.nc' 'SHA256' 'c23ad7fd11803b0fd77d40cee154faf87fea306ffed6174f3cc081b986a500e3'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_209101-209912.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/AFR-44/GERICS/MOHC-HadGEM2-ES/rcp85/r1i1p1/GERICS-REMO2009/v1/mon/tas/v20170620/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_GERICS-REMO2009_v1_mon_209101-209912.nc' 'SHA256' 'd1b8c7878222c05bc61a4b699e5a49062720eeb4a7a8e7c69fab4e0856ba2021'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20051201-20110101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/tas/v20151029/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20051201-20110101.nc' 'SHA256' 'f378504f34be6e6c4fef3886c3361f5af4ed3fe1a9c5a9b0cf9e94f5e1f6b406'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20110101-20210101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/tas/v20151029/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20110101-20210101.nc' 'SHA256' 'dd01d17914b853095544fec76c49ca35a9b61d9628c4b54d82591951e7af4e1e'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20210101-20310101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/tas/v20151029/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20210101-20310101.nc' 'SHA256' '80464c45f1131989e5d07b82fcdde2c6fdc38efb21c4012c5801f5b13bd2c176'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20310101-20410101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/tas/v20151029/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20310101-20410101.nc' 'SHA256' 'd821ff1914b35a7a1a490a638cdfa818af2773214ce46233266c971a21883a16'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20410101-20510101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/tas/v20151029/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20410101-20510101.nc' 'SHA256' 'b223c67a591ff1f3d0e2902e5ff5610c84de2485969675d0e5974a70d78338c7'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20510101-20610101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/tas/v20151029/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20510101-20610101.nc' 'SHA256' '6481b6b907da2a1c272ffc54f9ae2b11eee08ce45cae0628c11afffe040d66e0'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20610101-20710101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/tas/v20151029/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20610101-20710101.nc' 'SHA256' '16b52c822dd7896b964bf60b9c7d71b0ca16cf9693ab7f61465a04f640dd671f'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20710101-20810101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/tas/v20151029/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20710101-20810101.nc' 'SHA256' '7ce1c36d94e3676df0f3ca41a3d6a28989b6e799303303c94234d317790a61da'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20810101-20910101.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/tas/v20151029/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20810101-20910101.nc' 'SHA256' 'b497e3c2a1defbae5d21f7447b74f67c02e00c2243af890b07a5e96dc30fcfcb'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20910101-20991201.nc' 'http://esgf-ictp.hpc.cineca.it/thredds/fileServer/esg_dataroot/cordex/output/AFR-44/ICTP/MOHC-HadGEM2-ES/rcp85/r1i1p1/ICTP-RegCM4-3/v4/mon/tas/v20151029/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_ICTP-RegCM4-3_v4_mon_20910101-20991201.nc' 'SHA256' 'e88191eec6a96c4356be6afb13311e8aa4e9a21b449e04da96270840d5a3c11c'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_200601-201012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/tas/v20160802/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_200601-201012.nc' 'SHA256' '01a632a6491b74c7af21a0d4d54396443a76a4f199133f9e53c94ada648feadd'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_201101-202012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/tas/v20160802/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_201101-202012.nc' 'SHA256' 'fa1429c711eafeb6fec9a339220b08654c3c2f722ffdc827d1c054db16271634'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_202101-203012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/tas/v20160802/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_202101-203012.nc' 'SHA256' 'e4ff4480532d9a5f4decc123255c301a96978516e5ab24688c722fd155d743fe'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_203101-204012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/tas/v20160802/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_203101-204012.nc' 'SHA256' '4daa0fd51d1f6454d910d73114d63b041c42900e5f0bfbf265a482d92989d565'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_204101-205012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/tas/v20160802/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_204101-205012.nc' 'SHA256' '3571ba2618f21632529edd6d108e5263b556f8a447b1856a2365b9a06139bc1b'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_205101-206012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/tas/v20160802/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_205101-206012.nc' 'SHA256' '43917437aa79d40ef9f4cc3b072e72a77ed91cf341bd7cdccc640c98cd182e73'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_206101-207012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/tas/v20160802/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_206101-207012.nc' 'SHA256' 'b8c2af3a89bca11b097ad25833c8ddbf426905f55fba4cafbbab98837ac77cfc'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_207101-208012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/tas/v20160802/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_207101-208012.nc' 'SHA256' 'a71b5ebc5342e2fd4889b8828bfc8a3421cd33700aa79e412ea8cd2e69829269'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_208101-209012.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/tas/v20160802/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_208101-209012.nc' 'SHA256' '42a4496a902734749d1318475abecb155693fd1d2ac16d7205c793b8f655c0dc'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_209101-209912.nc' 'http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/AFR-44/KNMI/MOHC-HadGEM2-ES/rcp85/r1i1p1/KNMI-RACMO22T/v2/mon/tas/v20160802/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_KNMI-RACMO22T_v2_mon_209101-209912.nc' 'SHA256' '8aa5b04ee2a67516be5e208de6a6852682d87052947b62575ddf85daf7e4909a'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_200601-201012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_200601-201012.nc' 'SHA256' '16dfd03b948e98ecd108ed4f201a043d466e6fb90ee7e52c491329cbd1434e4e'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_201101-202012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_201101-202012.nc' 'SHA256' '2de9f826b8f13ef9e416e050404cae7d833357867be6534336e5b8b326f9fb08'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_202101-203012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_202101-203012.nc' 'SHA256' '92c21836af79581eca5ac534a6cabaeed02d02fa467aa189738e3424cc925537'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_203101-204012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_203101-204012.nc' 'SHA256' 'ff068564e7580fac1cc4ea6655d61bb984b59d009240aca3fdcf78b56c824898'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_204101-205012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_204101-205012.nc' 'SHA256' 'b058d96e718dc477d96c88f6120a32b48810f801356c16ac086e8dc912bfd673'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_205101-206012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_205101-206012.nc' 'SHA256' 'ab22bef9b9d11a04547fa77b16074940adcbc72a539f391b03e60cd3a677af72'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_206101-207012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_206101-207012.nc' 'SHA256' 'bb2ff2066c68e0b491fd80e6b88a31c55818725f7256098f74e819ca7407655d'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_207101-208012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_207101-208012.nc' 'SHA256' '0e851c92426dde20f616067280ac2e73b371af2a67057a739377f96a161b1bb4'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_208101-209012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_208101-209012.nc' 'SHA256' '6aa0559968ee3476db963508f1d9c6e6fa5d5fe36ebc95bf3c8a722e92764c7f'
'tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_209101-209912.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/MOHC-HadGEM2-ES/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_MOHC-HadGEM2-ES_rcp85_r1i1p1_SMHI-RCA4_v1_mon_209101-209912.nc' 'SHA256' '261f32e109ee47a240062c48f1df24760d6ca23f4a646de8a64af45442dbc129'
'tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_200601-201012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_200601-201012.nc' 'SHA256' '51d143437f324bdec7a0caa84d2e0e0b1db62ba933725487b28a766c61935d05'
'tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_201101-202012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_201101-202012.nc' 'SHA256' 'ca4e861f0d628e78b20ac90a8a5caf2aea79d02d58acebdc022c14b303a1d076'
'tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_202101-203012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_202101-203012.nc' 'SHA256' '1189579f21f087a9c9515a995b2d23ee5784e6a884c8d7f26de8023e9973dc43'
'tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_203101-204012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_203101-204012.nc' 'SHA256' 'b668f415db7e008e4939f41445a199a419ca9d6e013bf77b42481293d0953004'
'tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_204101-205012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_204101-205012.nc' 'SHA256' 'd5e687c07157c9ec2c6739b5f9e8f4f8c83d00f3989c1fec000a281c0ce99e90'
'tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_205101-206012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_205101-206012.nc' 'SHA256' 'ca33e6865d687227393bd92b3161b998d1e2a03c3a8af4ef5ce172405e3bb19b'
'tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_206101-207012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_206101-207012.nc' 'SHA256' '0532c16283177b53214b5fc58d876c3f53586d19c06d2f08a2dd8b4ad55da267'
'tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_207101-208012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_207101-208012.nc' 'SHA256' '52a2e14287665666eb281dd1de2d2d82504c7f794ea405a622612c7237c68eae'
'tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_208101-209012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_208101-209012.nc' 'SHA256' '566145f841cd37f1037ab35e1c197afef14ce64221ee80bb0b00fe935ec47db7'
'tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_209101-210012.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot1/cordexdata/cordex/output/AFR-44/SMHI/NCC-NorESM1-M/rcp85/r1i1p1/SMHI-RCA4/v1/mon/tas/v20130927/tas_AFR-44_NCC-NorESM1-M_rcp85_r1i1p1_SMHI-RCA4_v1_mon_209101-210012.nc' 'SHA256' '686e175bc17a7c684133248582aa5a12d676e539839260a388b3815a38ddc31a'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 60 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
